#ifndef BITS_H
#define BITS_H
#include "d_types.h"
#include <strings.h>

/**
 * @defgroup d_bits Bit Manipulation
 * @{
 * @brief Fixed-width bit-field types and a portable bit-manipulation API.
 *
 * Provides four typed bit-field aliases (::DBits8 … ::DBits64) and a uniform
 * set of inline helpers for each width, generated by the @ref D_BITS_X_API
 * macro. Also provides standalone utilities for locating and clearing the
 * most-significant and least-significant set bits.
 *
 * @par Generated API summary (replace @c d_bits_8 with @c d_bits_16 / @c d_bits_32 / @c d_bits_64)
 * | Function                              | Description                            |
 * |---------------------------------------|----------------------------------------|
 * | `d_bits_8_check_bits_set(val, mask)`  | True if every bit in @p mask is set    |
 * | `d_bits_8_set_bits(&val, mask)`       | OR @p mask into @p val                 |
 * | `d_bits_8_unset_bits(&val, mask)`     | AND-NOT @p mask from @p val            |
 * | `d_bits_8_assign(&val, bits)`         | Replace @p val with @p bits            |
 * | `d_bits_8_toggle_bit(&val, n)`        | Flip bit @p n (0-based)                |
 * | `d_bits_8_clear_bit(&val, n)`         | Clear bit @p n (0-based)               |
 * | `d_bits_8_reset_all_bits(&val)`       | Zero all bits                          |
 *
 * @par Typical lifecycle
 * @code{.c}
 *   DBits8 flags = 0;
 *   d_bits_8_set_bits(&flags, 0x03);          // flags == 0b00000011
 *   d_bits_8_toggle_bit(&flags, 1);           // flags == 0b00000001
 *   d_bits_8_check_bits_set(flags, 0x01);     // true
 *   d_bits_8_reset_all_bits(&flags);          // flags == 0
 * @endcode
 */



/* -----------------------------------------------------------------------
 * Compiler built-in detection
 * -------------------------------------------------------------------- */

#if defined(__has_builtin)

#if __has_builtin(__builtin_ffs)
#define USE_BUILTIN_FFS 1
#else
#define USE_BUILTIN_FFS 0
#endif

#if __has_builtin(__builtin_ffsll)
#define USE_BUILTIN_FFSLL 1
#else
#define USE_BUILTIN_FFSLL 0
#endif

#endif

/* -----------------------------------------------------------------------
 * Low-level bit macros
 * -------------------------------------------------------------------- */

/**
 * @brief Evaluates to @p bits with bit @p bit flipped (XOR).
 *
 * Does not modify @p bits in place; use the result.
 * @warning Arguments are not parenthesized — pass plain variables or
 *          fully-parenthesized sub-expressions to avoid operator-precedence
 *          surprises (e.g. `D_TOGGLE_BIT(a | b, n)` is unsafe).
 */
#define D_TOGGLE_BIT(bits, bit) (bits ^ ((usize)1 << bit))

/**
 * @brief Evaluates to @p bits with bit @p bit cleared (AND NOT).
 *
 * Does not modify @p bits in place; use the result.
 * @warning Arguments are not parenthesized — pass plain variables or
 *          fully-parenthesized sub-expressions to avoid operator-precedence
 *          surprises (e.g. `D_CLEAR_BIT(a | b, n)` is unsafe).
 */
#define D_CLEAR_BIT(bits, bit) (bits & ~((usize)1 << bit))

/* -----------------------------------------------------------------------
 * Typed bit-field aliases
 * -------------------------------------------------------------------- */

/** @brief  8-bit bit-field type. */
typedef uint8_t DBits8;
/** @brief 16-bit bit-field type. */
typedef uint16_t DBits16;
/** @brief 32-bit bit-field type. */
typedef uint32_t DBits32;
/** @brief 64-bit bit-field type. */
typedef uint64_t DBits64;

/* -----------------------------------------------------------------------
 * D_BITS_X_API — generates the full per-width inline API
 * -------------------------------------------------------------------- */

/**
 * @brief Generates the complete bit-manipulation API for one fixed-width type.
 *
 * Calling `D_BITS_X_API(d_bits_8, u8, 8)` produces the following inline
 * functions (substitute @c d_bits_8 / @c u8 / @c 8 for other widths):
 *
 * ---
 *
 * **`bool d_bits_8_check_bits_set(u8 bits_set, const u8 bits_to_check)`**
 *
 * Returns @c true if every bit in @p bits_to_check is set in @p bits_set
 * (i.e. `(bits_set & bits_to_check) == bits_to_check`).
 *
 * ---
 *
 * **`bool d_bits_8_set_bits(u8 *bits_set, const u8 bits_to_set)`**
 *
 * OR-sets @p bits_to_set into @p *bits_set. Returns @c false if
 * @p bits_set is NULL, @c true otherwise.
 *
 * ---
 *
 * **`bool d_bits_8_unset_bits(u8 *bits_set, const u8 bits_to_unset)`**
 *
 * Clears (AND-NOT) @p bits_to_unset from @p *bits_set. Returns @c false if
 * @p bits_set is NULL, @c true otherwise.
 *
 * ---
 *
 * **`bool d_bits_8_assign(u8 *bits_set, u8 bits)`**
 *
 * Replaces @p *bits_set with @p bits. Returns @c false if @p bits_set is
 * NULL, @c true otherwise.
 *
 * ---
 *
 * **`bool d_bits_8_toggle_bit(u8 *bits_set, usize bit)`**
 *
 * Flips bit at 0-based position @p bit in @p *bits_set. Returns @c false
 * if @p bits_set is NULL or @p bit >= 8.
 *
 * ---
 *
 * **`bool d_bits_8_clear_bit(u8 *bits_set, usize bit)`**
 *
 * Clears bit at 0-based position @p bit in @p *bits_set. Returns @c false
 * if @p bits_set is NULL or @p bit >= 8.
 *
 * ---
 *
 * **`bool d_bits_8_reset_all_bits(u8 *bits_set)`**
 *
 * Sets @p *bits_set to 0. Returns @c false if @p bits_set is NULL,
 * @c true otherwise.
 *
 * @param NAME    Prefix for all generated function names (e.g. @c d_bits_8).
 * @param TYPE    Underlying unsigned integer type (e.g. @c u8).
 * @param NB_BITS Width in bits used to range-check @c toggle_bit / @c clear_bit.
 */
#define D_BITS_X_API(NAME, TYPE, NB_BITS)                                             \
    static inline bool NAME##_check_bits_set(TYPE bits_set, const TYPE bits_to_check) \
    {                                                                                 \
        return (bits_set & bits_to_check) == bits_to_check;                           \
    }                                                                                 \
                                                                                      \
    static inline bool NAME##_set_bits(TYPE *bits_set, const TYPE bits_to_set)        \
    {                                                                                 \
        if (!bits_set)                                                                \
            return false;                                                             \
        *bits_set = *bits_set | bits_to_set;                                          \
        return true;                                                                  \
    }                                                                                 \
    static inline bool NAME##_unset_bits(TYPE *bits_set, const TYPE bits_to_unset)    \
    {                                                                                 \
        if (!bits_set)                                                                \
            return false;                                                             \
        *bits_set = *bits_set & ~bits_to_unset;                                       \
        return true;                                                                  \
    }                                                                                 \
    static inline bool NAME##_assign(TYPE *bits_set, TYPE bits)                       \
    {                                                                                 \
        if (!bits_set)                                                                \
            return false;                                                             \
        *bits_set = bits;                                                             \
        return true;                                                                  \
    }                                                                                 \
    static inline bool NAME##_toggle_bit(TYPE *bits_set, usize bit)                   \
    {                                                                                 \
        if (!bits_set || bit >= (usize)NB_BITS)                                       \
            return false;                                                             \
        *bits_set = D_TOGGLE_BIT(*bits_set, bit);                                     \
        return true;                                                                  \
    }                                                                                 \
    static inline bool NAME##_clear_bit(TYPE *bits_set, usize bit)                    \
    {                                                                                 \
        if (!bits_set || bit >= (usize)NB_BITS)                                       \
            return false;                                                             \
        *bits_set = D_CLEAR_BIT(*bits_set, bit);                                      \
        return true;                                                                  \
    }                                                                                 \
    static inline bool NAME##_reset_all_bits(TYPE *bits_set)                          \
    {                                                                                 \
        if (!bits_set)                                                                \
            return false;                                                             \
        *bits_set = 0;                                                                \
        return true;                                                                  \
    }

/** @brief Instantiates the full bit API for ::DBits8 (prefix @c d_bits_8). */
D_BITS_X_API(d_bits_8, u8, 8)
/** @brief Instantiates the full bit API for ::DBits16 (prefix @c d_bits_16). */
D_BITS_X_API(d_bits_16, u16, 16)
/** @brief Instantiates the full bit API for ::DBits32 (prefix @c d_bits_32). */
D_BITS_X_API(d_bits_32, u32, 32)
/** @brief Instantiates the full bit API for ::DBits64 (prefix @c d_bits_64). */
D_BITS_X_API(d_bits_64, u64, 64)

/* -----------------------------------------------------------------------
 * Bit scan and clear utilities
 * -------------------------------------------------------------------- */

/**
 * @brief Evaluates to @p value with the least-significant set bit cleared.
 *
 * Uses the identity `(value) & ((value) - 1)`. Expands to an expression;
 * @p value is expanded twice — avoid passing expressions with side effects.
 * The result expression is not wrapped in outer parentheses, so embedding it
 * inside a larger expression may produce precedence surprises; assign to a
 * variable first when in doubt.
 *
 * @code{.c}
 *   int v = 0b1010;
 *   v = d_bits_clear_least_significant_bit_set(v); // v == 0b1000
 * @endcode
 */
#define d_bits_clear_least_significant_bit_set(value) ((value) &((value) - 1))

/* Fills every bit below the MSB with 1 (32-bit range). */
static inline long long int __d_bits_smear_int(long long int value)
{
    // e.g. value = 0b10110000
    value |= value >> 1;  // 0b10110000 | 0b01011000 = 0b11111000
    value |= value >> 2;  // 0b11111000 | 0b00111110 = 0b11111110
    value |= value >> 4;  // 0b11111110 | 0b00001111 = 0b11111111
    value |= value >> 8;  // 0b11111111 | 0b00000000 = 0b11111111
    value |= value >> 16; // 0b11111111 | 0b00000000 = 0b11111111
    return value;
}

/* Fills every bit below the MSB with 1 (64-bit range). */
static inline long long int __d_bits_smear_ll(long long int value)
{
    value = __d_bits_smear_int(value);
    value |= value >> 32; // fills remaining lower 32 bits → all bits below MSB are 1
    return value;
}

/**
 * @brief Returns @p value with the most-significant set bit cleared.
 *
 * Calls @ref __d_bits_smear_int on @p value to produce a mask @p v in which
 * every bit below the MSB is 1. Then returns `value & (v >> 1)`, which keeps
 * all bits of the original @p value except the MSB.
 *
 * @note Despite the @c _int suffix the actual parameter type is
 *       @c long @c long @c int; the smear operates across a 64-bit range.
 *       The return type is @c int (lower 32 bits).
 *
 * @param value Integer to process.
 * @return @p value with its most-significant set bit cleared;
 *         0 if @p value is 0 or has only one bit set.
 *
 * @code{.c}
 *   int v = d_bits_clear_most_significant_bit_set_int(0b1010); // 0b0010
 * @endcode
 */
static inline int d_bits_clear_most_significant_bit_set_int(int value)
{
    long long int v = __d_bits_smear_int(value);
    return value & (v >> 1);
}

/**
 * @brief Returns @p value with the most-significant set bit cleared (64-bit).
 *
 * 64-bit variant of @ref d_bits_clear_most_significant_bit_set_int.
 *
 * @param value 64-bit signed integer to process.
 * @return @p value with its MSB cleared; 0 if @p value is 0 or has only one bit set.
 */
static inline long long int d_bits_clear_most_significant_bit_set_ll(long long int value)
{
    long long int v = __d_bits_smear_ll(value);
    return value & (v >> 1);
}

/**
 * @brief Returns the 1-based bit position of the least-significant set bit (32-bit).
 *
 * Equivalent to POSIX @c ffs(). Uses @c __builtin_ffs when available; falls
 * back to a byte-level lookup table otherwise.
 *
 * @param value Integer to scan.
 * @return 1-based index of the lowest set bit (bit 0 → returns 1), or 0 if
 *         @p value is 0.
 *
 * @code{.c}
 *   d_bits_get_index_least_significant_bit_set_int(0b1100); // returns 3
 * @endcode
 */
static inline int d_bits_get_index_least_significant_bit_set_int(int value)
{
#if USE_BUILTIN_FFS
    return __builtin_ffs(value);
#else
    static const unsigned char table[] =
        {
            0, 1, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
            6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
            7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
            7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
            8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
            8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
            8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
            8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8};
    unsigned int a;
    unsigned int x = value & -value; // keep only the lowest set bit.

    a = x <= 0xffff ? (x <= 0xff ? 0 : 8) : (x <= 0xffffff ? 16 : 24);

    return table[x >> a] + a;
#endif
}

/**
 * @brief Returns the 1-based bit position of the least-significant set bit (64-bit).
 *
 * Equivalent to POSIX @c ffsll(). Uses @c __builtin_ffsll when available;
 * falls back to splitting into two 32-bit scans otherwise.
 *
 * @param value 64-bit integer to scan.
 * @return 1-based index of the lowest set bit, or 0 if @p value is 0.
 *
 * @code{.c}
 *   d_bits_get_index_least_significant_bit_set_ll(0x100000000LL); // returns 33
 * @endcode
 */
static inline int d_bits_get_index_least_significant_bit_set_ll(long long int value)
{
#if USE_BUILTIN_FFSLL
    return __builtin_ffsll(value);
#else
    usize x = value & -value;

    if (x <= 0xffffffff)
        return d_bits_get_index_least_significant_bit_set_int(value);
    else
        return 32 + d_bits_get_index_least_significant_bit_set_int(value >> 32);
#endif
}

/**
 * @brief Returns the 1-based bit position of the most-significant set bit.
 *
 * @note Despite the @c _int suffix the parameter type is @c long @c long @c int;
 *       the internal smear operates in 64-bit range.  The return value is still
 *       bounded by the actual bit-width of @p value.
 *
 * @param value 64-bit integer to scan.
 * @return 1-based index of the highest set bit (bit 0 → returns 1), or 0 if
 *         @p value is 0.
 *
 * @code{.c}
 *   d_bits_get_index_most_significant_bit_set_int(0b1010); // returns 4
 * @endcode
 */
static inline int d_bits_get_index_most_significant_bit_set_int(long long int value)
{
    long long int v = __d_bits_smear_int(value);
    return d_bits_get_index_least_significant_bit_set_int(v ^ (v >> 1));
}

/**
 * @brief Returns the 1-based bit position of the most-significant set bit (64-bit).
 *
 * 64-bit variant of @ref d_bits_get_index_most_significant_bit_set_int.
 *
 * @param value 64-bit integer to scan.
 * @return 1-based index of the highest set bit, or 0 if @p value is 0.
 *
 * @code{.c}
 *   d_bits_get_index_most_significant_bit_set_ll(0xB00000000LL); // returns 36
 * @endcode
 */
static inline int d_bits_get_index_most_significant_bit_set_ll(long long int value)
{
    long long int v = __d_bits_smear_ll(value);
    return d_bits_get_index_least_significant_bit_set_ll(v ^ (v >> 1));
}

/** @} */ /* end of d_bits group */

#endif
