#ifndef D_HASH_SET
#define D_HASH_SET

/**
 * @defgroup d_hash_set Hash Set
 * @{
 * @brief Open-addressing hash set with Swiss-table-style group probing.
 *
 * ::DHashSet stores unique keys of a fixed size with O(1) average-case
 * insert, lookup, and delete. Keys are copied by value into the internal
 * table; the caller's key variable is never referenced after a call returns.
 *
 * @par Ownership model
 * Two destructor callbacks are available at initialisation time:
 *  - **key_destructor_fn** — called when a key is evicted from the table.
 *    If the key owns heap memory (e.g. `char *`), supply a destructor to free it.
 *    Pass NULL for plain-value keys (integers, structs, …).
 *  - **value_destructor_fn** — the hash set stores no values; this parameter
 *    is accepted for API symmetry with ::DUnorderedMap but is effectively unused.
 *    Pass NULL.
 *
 * @par Not-owned vs. owned keys
 * The library provides two families of convenience constructors generated by
 * the macros @ref D_HASH_SET_INIT_WITH_NOT_OWNED_KEY and
 * @ref D_HASH_SET_INIT_WITH_OWNED_KEY.
 *
 * **Not-owned** (`d_hash_set_init_not_owned_<type>_key`): The set stores a
 * copy of the key bytes and does not free them on removal. Suitable for
 * integer keys, @c char keys, ::DStringView, and any type whose lifetime is
 * managed externally.
 *
 * **Owned** (`d_hash_set_init_owned_<type>_key`): The set calls the
 * appropriate destructor when a key is removed or the set is destroyed.
 * Provided for `char *` and `DDynString *` keys.
 *
 * @par remove vs. delete
 *  - @ref d_hash_set_remove — transfers the stored key bytes to the caller's
 *    buffer; **no** destructor is called. Use when you want to take ownership.
 *  - @ref d_hash_set_delete — calls the key destructor (if any) and discards
 *    the key. Use when the set should free the key.
 *
 * @par Typical lifecycle (integer keys)
 * @code{.c}
 *   DHashSet set;
 *   d_hash_set_init_not_owned_int32_key(&set, 64, NULL);
 *
 *   int32 k = 42;
 *   d_hash_set_insert(&set, &k);
 *
 *   if (d_hash_set_key_exists(&set, &k))
 *       puts("42 is in the set");
 *
 *   d_hash_set_delete(&set, &k);
 *   d_hash_set_destroy(&set);
 * @endcode
 *
 * @par Typical lifecycle (owned string keys)
 * @code{.c}
 *   DHashSet set;
 *   d_hash_set_init_owned_str_key(&set, 16, NULL);
 *
 *   char *key = strdup("hello"); // set takes ownership on insert
 *   d_hash_set_insert(&set, &key);
 *
 *   char *lookup = "hello";
 *   if (d_hash_set_key_exists(&set, &lookup))
 *       puts("found");
 *
 *   d_hash_set_destroy(&set); // frees "hello" via _free_str
 * @endcode
 */
#include "d_error.h"
#include "d_types.h"
#include "d_general_lib.h"
#include "d_hash_utils.h"
#include "raw_map.h"

/**
 * @brief Open-addressing hash set.
 *
 * Do not access internal fields directly; use the @ref d_hash_set API.
 */
typedef struct DHashSet
{
    RawMap raw_map; /**< Underlying hash map (keys only; implementation detail). */
} DHashSet;

/* -----------------------------------------------------------------------
 * Construction macros
 * -------------------------------------------------------------------- */

/**
 * @brief Generates a not-owned-key convenience constructor for a specific key type.
 *
 * The generated function has the signature:
 * @code{.c}
 *   DResult d_hash_set_init_not_owned_<KEY_NAME>_key(
 *       DHashSet *d_hash_set,
 *       usize     capacity,
 *       DestroyElemFn value_destructor_fn); // always pass NULL
 * @endcode
 *
 * The pre-instantiated types are: @c int8, @c int16, @c int32, @c int64,
 * @c u8, @c u16, @c u32, @c u64, @c usize, @c bool, @c char,
 * @c d_string_view, @c d_dyn_string (not-owned pointer).
 *
 * @param KEY_NAME  Token used in the generated function name.
 * @param KEY_TYPE  Underlying C type of the key.
 */
#define D_HASH_SET_INIT_WITH_NOT_OWNED_KEY(KEY_NAME, KEY_TYPE)                                                                              \
    static inline DResult d_hash_set_init_not_owned_##KEY_NAME##_key(DHashSet *d_hash_set, usize capacity, DestroyElemFn key_destructor_fn) \
    {                                                                                                                                       \
        return d_hash_set_init(d_hash_set, sizeof(KEY_TYPE), capacity, hash_##KEY_NAME##_key, compare_##KEY_NAME, key_destructor_fn);       \
    }

/**
 * @brief Generates an owned-key convenience constructor for a specific key type.
 *
 * The generated function has the signature:
 * @code{.c}
 *   DResult d_hash_set_init_owned_<KEY_NAME>_key(
 *       DHashSet *d_hash_set,
 *       usize     capacity,
 *       DestroyElemFn value_destructor_fn); // always pass NULL
 * @endcode
 *
 * The pre-instantiated types are: @c str (@c char *) and @c d_dyn_string
 * (@c DDynString *).
 *
 * @param KEY_NAME       Token used in the generated function name.
 * @param KEY_TYPE       Underlying C type of the key.
 * @param KEY_DESTRUCTOR Function called to free a key when it is removed or overwritten.
 */
#define D_HASH_SET_INIT_WITH_OWNED_KEY(KEY_NAME, KEY_TYPE, KEY_DESTRUCTOR)                                                         \
    static inline DResult d_hash_set_init_owned_##KEY_NAME##_key(DHashSet *d_hash_set, usize capacity)                             \
    {                                                                                                                              \
        return d_hash_set_init(d_hash_set, sizeof(KEY_TYPE), capacity, hash_##KEY_NAME##_key, compare_##KEY_NAME, KEY_DESTRUCTOR); \
    }

/**
 * @brief Low-level initialisation with full control over hash, compare, and destructor.
 *
 * Prefer the typed convenience constructors generated by
 * @ref D_HASH_SET_INIT_WITH_NOT_OWNED_KEY and @ref D_HASH_SET_INIT_WITH_OWNED_KEY
 * unless you need a custom key type.
 *
 * @param d_hash_set           Hash set to initialise. Must not be NULL.
 * @param  key_size             Size in bytes of each key. Must be > 0.
 * @param  capacity             Initial capacity hint (the implementation may round up).
 * @param  hash_fn              Hash function for the key type. Must not be NULL.
 * @param  cmp_fn               Equality function for the key type. Must not be NULL.
 * @param  key_destructor_fn    Called when a key is removed/overwritten. May be NULL.
 * @param  value_destructor_fn  Unused by the hash set; pass NULL.
 * @return ::D_OK, ::D_ERR_INVALID_ARG if required arguments are NULL,
 *         ::D_ERR_ALLOC on allocation failure.
 */
DResult d_hash_set_init(DHashSet *d_hash_set, usize key_size, usize capacity, FnPtrGenHash hash_fn, FnPtrCmpKey cmp_fn, DestroyElemFn key_destructor_fn);

/* Pre-instantiated not-owned constructors */
D_HASH_SET_INIT_WITH_NOT_OWNED_KEY(int8, int8)
D_HASH_SET_INIT_WITH_NOT_OWNED_KEY(int16, int16)
D_HASH_SET_INIT_WITH_NOT_OWNED_KEY(int32, int32)
D_HASH_SET_INIT_WITH_NOT_OWNED_KEY(int64, int64)
D_HASH_SET_INIT_WITH_NOT_OWNED_KEY(u8, u8)
D_HASH_SET_INIT_WITH_NOT_OWNED_KEY(u16, u16)
D_HASH_SET_INIT_WITH_NOT_OWNED_KEY(u32, u32)
D_HASH_SET_INIT_WITH_NOT_OWNED_KEY(u64, u64)
D_HASH_SET_INIT_WITH_NOT_OWNED_KEY(usize, usize)
D_HASH_SET_INIT_WITH_NOT_OWNED_KEY(bool, bool)
D_HASH_SET_INIT_WITH_NOT_OWNED_KEY(char, char)
D_HASH_SET_INIT_WITH_NOT_OWNED_KEY(d_string_view, DStringView)
D_HASH_SET_INIT_WITH_NOT_OWNED_KEY(d_dyn_string, DDynString *)

/* Pre-instantiated owned constructors */
D_HASH_SET_INIT_WITH_OWNED_KEY(str, char *, _free_str)
D_HASH_SET_INIT_WITH_OWNED_KEY(d_dyn_string, DDynString *, (DestroyElemFn)d_dyn_string_destroy)

/* -----------------------------------------------------------------------
 * Operations
 * -------------------------------------------------------------------- */

/**
 * @brief Inserts a copy of @p key into the set.
 *
 * If the key already exists the existing entry is kept and the call is a
 * no-op (the set stores unique keys).
 *
 * @param map The hash set to insert into. Must not be NULL.
 * @param     key Pointer to the key to copy. Must not be NULL.
 * @return ::D_OK, ::D_ERR_INVALID_ARG if either argument is NULL,
 *         ::D_ERR_ALLOC on allocation failure (e.g. during a rehash).
 *
 * @code{.c}
 *   int32 k = 7;
 *   d_hash_set_insert(&set, &k);
 * @endcode
 */
DResult d_hash_set_insert(DHashSet *map, void *key);

/**
 * @brief Returns @c true if @p key is present in the set.
 *
 * @param map The hash set to query. Must not be NULL.
 * @param key Pointer to the key to look up. Must not be NULL.
 * @return @c true if found, @c false if not found or if any argument is NULL.
 *
 * @code{.c}
 *   int32 k = 7;
 *   if (d_hash_set_key_exists(&set, &k))
 *       puts("7 is in the set");
 * @endcode
 */
bool d_hash_set_key_exists(const DHashSet *map, void *key);

/**
 * @brief Removes @p key from the set and calls the key destructor (if any).
 *
 * Use this when you want the set to free the key's resources.
 *
 * @param map The hash set to delete from. Must not be NULL.
 * @param     key Pointer to the key to remove. Must not be NULL.
 * @return ::D_OK, ::D_ERR_INVALID_ARG if either argument is NULL,
 *         ::D_ERR_NOT_EXIST if the key is not in the set.
 *
 * @code{.c}
 *   int32 k = 7;
 *   d_hash_set_delete(&set, &k); // destructor called if configured
 * @endcode
 */
DResult d_hash_set_delete(DHashSet *map, void *key);

/**
 * @brief Removes @p key from the set and copies it into @p slot_key
 *        **without** calling the destructor.
 *
 * Use this when you want to take ownership of the stored key bytes.
 *
 * @param map      The hash set to remove from. Must not be NULL.
 * @param     key      Pointer to the key to look up. Must not be NULL.
 * @param    slot_key Buffer that receives the stored key bytes.
 *                         Must not be NULL and must be at least @c key_size bytes.
 * @return ::D_OK, ::D_ERR_INVALID_ARG if any argument is NULL,
 *         ::D_ERR_NOT_EXIST if the key is not in the set.
 *
 * @code{.c}
 *   char *lookup = "hello";
 *   char *taken  = NULL;
 *   d_hash_set_remove(&set, &lookup, &taken); // no destructor; caller owns taken
 *   free(taken);
 * @endcode
 */
DResult d_hash_set_remove(DHashSet *map, void *key, void *slot_key);

/**
 * @brief Writes the current number of keys in the set into @p size.
 *
 * @param  d_hash_set Hash set to query. Must not be NULL.
 * @param size       Receives the key count. Must not be NULL.
 * @return ::D_OK, ::D_ERR_INVALID_ARG if either argument is NULL.
 */
DResult d_hash_set_get_size(const DHashSet *d_hash_set, usize *size);

/**
 * @brief Writes the current table capacity into @p capacity.
 *
 * @param  d_hash_set Hash set to query. Must not be NULL.
 * @param capacity   Receives the capacity. Must not be NULL.
 * @return ::D_OK, ::D_ERR_INVALID_ARG if either argument is NULL.
 */
DResult d_hash_set_get_capacity(const DHashSet *d_hash_set, usize *capacity);

/**
 * @brief Calls the key destructor for all remaining entries, frees the table,
 *        and zeroes the struct.
 *
 * Safe to call on a NULL pointer (no-op). After this call @p map must not be
 * used without re-initialisation.
 *
 * @param map Hash set to destroy. May be NULL.
 */
void d_hash_set_destroy(DHashSet *map);

/** @} */ /* end of d_hash_set group */

#endif
