#ifndef D_UNORDERED_MAP
#define D_UNORDERED_MAP

/**
 * @defgroup d_unordered_map Unordered Map
 * @{
 * @brief Open-addressing hash map with Swiss-table-style group probing.
 *
 * ::DUnorderedMap stores key-value pairs where both the key and value types
 * are chosen at initialisation time. Keys and values are copied by value into
 * the internal table — `key_size` and `value_size` bytes are memcpy'd on
 * insert. Neither pointer is referenced after a call returns.
 *
 * @par Ownership model
 * Two optional destructor callbacks are available:
 *  - **key_destructor_fn** — called when a key is evicted (on delete,
 *    overwrite, or destroy). Pass NULL for plain-value keys.
 *  - **value_destructor_fn** — called when a value is evicted under the
 *    same conditions. Pass NULL if values do not own resources.
 *
 * @par Not-owned vs. owned keys
 * Two families of convenience constructors are generated by the macros
 * @ref D_UNORDERED_MAP_INIT_WITH_NOT_OWNED_KEY and
 * @ref D_UNORDERED_MAP_INIT_WITH_OWNED_KEY.
 *
 * **Not-owned** (`d_unordered_map_init_not_owned_<type>_key`): No destructor
 * is registered for the key. Suitable for integer keys, ::DStringView, and
 * any type managed externally.
 *
 * **Owned** (`d_unordered_map_init_owned_<type>_key`): A type-specific
 * destructor is registered. Provided for `char *` and `DDynString *` keys.
 *
 * @par Duplicate-insert behaviour
 * Inserting a key that already exists **updates** the stored value.
 * Both the old key's and the old value's destructors are called (if configured)
 * before the new pair is written.
 *
 * @par remove vs. delete
 *  - @ref d_unordered_map_remove — copies the stored key and value to caller-
 *    supplied buffers and removes the entry. **No** destructor is called.
 *    Use when you want to take ownership of the stored data.
 *  - @ref d_unordered_map_delete — calls both destructors (if configured) and
 *    removes the entry. Use when the map should free the resources.
 *
 * @par get pointer lifetime
 * @ref d_unordered_map_get returns a pointer directly into the map's internal
 * storage. This pointer is **invalidated** by any subsequent insert operation
 * (which may trigger a rehash). Do not store it across insertions.
 *
 * @par Typical lifecycle (int → int)
 * @code{.c}
 *   DUnorderedMap map;
 *   d_unordered_map_init_not_owned_int32_key(&map, sizeof(int), 64, NULL);
 *
 *   int32 k = 1; int v = 100;
 *   d_unordered_map_insert(&map, &k, &v);
 *
 *   int *got = d_unordered_map_get(&map, &k); // got != NULL, *got == 100
 *
 *   d_unordered_map_delete(&map, &k);
 *   d_unordered_map_destroy(&map);
 * @endcode
 *
 * @par Typical lifecycle (owned string keys → int values)
 * @code{.c}
 *   DUnorderedMap map;
 *   d_unordered_map_init_owned_str_key(&map, sizeof(int), 16, NULL);
 *
 *   char *key = strdup("answer");  // map takes ownership on insert
 *   int   val = 42;
 *   d_unordered_map_insert(&map, &key, &val);
 *
 *   char *lookup = "answer";
 *   int  *found  = d_unordered_map_get(&map, &lookup);
 *
 *   d_unordered_map_destroy(&map); // frees "answer" via _free_str
 * @endcode
 */
#include "d_error.h"
#include "d_types.h"
#include "d_hash_utils.h"
#include "d_general_lib.h"

/**
 * @brief Open-addressing hash map.
 *
 * Do not access internal fields directly; use the @ref d_unordered_map API.
 */
typedef struct DUnorderedMap
{
    RawMap raw_map; /**< Underlying hash table (implementation detail). */
} DUnorderedMap;

/**
 * @brief Low-level initialisation with full control over all parameters.
 *
 * Prefer the typed convenience constructors generated by
 * @ref D_UNORDERED_MAP_INIT_WITH_NOT_OWNED_KEY and
 * @ref D_UNORDERED_MAP_INIT_WITH_OWNED_KEY unless you need a custom key type.
 *
 * @param d_unordered_map    Map to initialise. Must not be NULL.
 * @param  key_size           Size in bytes of each key. Must be > 0.
 * @param  value_size         Size in bytes of each value. Must be > 0.
 * @param  capacity           Initial capacity hint (may be rounded up internally).
 * @param  hash_fn            Hash function for the key type. Must not be NULL.
 * @param  cmp_fn             Equality function for the key type. Must not be NULL.
 * @param  key_destructor_fn  Destructor for evicted keys. May be NULL.
 * @param  value_destructor_fn Destructor for evicted values. May be NULL.
 * @return ::D_OK, ::D_ERR_INVALID_ARG if required arguments are NULL,
 *         ::D_ERR_ALLOC on allocation failure.
 */
DResult d_unordered_map_init(DUnorderedMap *d_unordered_map, usize key_size, usize value_size, usize capacity, FnPtrGenHash hash_fn, FnPtrCmpKey cmp_fn, FnPtrFreeElem key_destructor_fn, FnPtrFreeElem value_destructor_fn);

/* -----------------------------------------------------------------------
 * Construction macros
 * -------------------------------------------------------------------- */

/**
 * @brief Generates a not-owned-key convenience constructor for a specific key type.
 *
 * The generated function has the signature:
 * @code{.c}
 *   DResult d_unordered_map_init_not_owned_<KEY_NAME>_key(
 *       DUnorderedMap *d_unordered_map,
 *       usize          value_size,
 *       usize          capacity,
 *       FnPtrFreeElem  value_destructor_fn);
 * @endcode
 *
 * Pre-instantiated types: @c int8, @c int16, @c int32, @c int64,
 * @c u8, @c u16, @c u32, @c u64, @c usize, @c bool, @c char,
 * @c str (@c char *, not-owned), @c d_dyn_string (@c DDynString *, not-owned),
 * @c d_string_view.
 *
 * @param KEY_NAME  Token used in the generated function name.
 * @param KEY_TYPE  Underlying C type of the key.
 */
#define D_UNORDERED_MAP_INIT_WITH_NOT_OWNED_KEY(KEY_NAME, KEY_TYPE)                                                                                            \
    static inline DResult d_unordered_map_init_not_owned_##KEY_NAME##_key(DUnorderedMap *d_unordered_map, usize value_size, usize capacity, FnPtrFreeElem value_destructor_fn) \
    {                                                                                                                                                          \
        return d_unordered_map_init(d_unordered_map, sizeof(KEY_TYPE), value_size, capacity, hash_##KEY_NAME##_key, compare_##KEY_NAME, NULL, value_destructor_fn);            \
    }

/**
 * @brief Generates an owned-key convenience constructor for a specific key type.
 *
 * The generated function has the signature:
 * @code{.c}
 *   DResult d_unordered_map_init_owned_<KEY_NAME>_key(
 *       DUnorderedMap *d_unordered_map,
 *       usize          value_size,
 *       usize          capacity,
 *       FnPtrFreeElem  value_destructor_fn);
 * @endcode
 *
 * Pre-instantiated types: @c str (@c char *) and @c d_dyn_string (@c DDynString *).
 *
 * @param KEY_NAME       Token in the generated function name.
 * @param KEY_TYPE       Underlying C type of the key.
 * @param KEY_DESTRUCTOR Destructor called when a key is evicted or overwritten.
 */
#define D_UNORDERED_MAP_INIT_WITH_OWNED_KEY(KEY_NAME, KEY_TYPE, KEY_DESTRUCTOR)                                                                               \
    static inline DResult d_unordered_map_init_owned_##KEY_NAME##_key(DUnorderedMap *d_unordered_map, usize value_size, usize capacity, FnPtrFreeElem value_destructor_fn)    \
    {                                                                                                                                                         \
        return d_unordered_map_init(d_unordered_map, sizeof(KEY_TYPE), value_size, capacity, hash_##KEY_NAME##_key, compare_##KEY_NAME, KEY_DESTRUCTOR, value_destructor_fn); \
    }

/* Pre-instantiated not-owned constructors */
D_UNORDERED_MAP_INIT_WITH_NOT_OWNED_KEY(int8,          int8)
D_UNORDERED_MAP_INIT_WITH_NOT_OWNED_KEY(int16,         int16)
D_UNORDERED_MAP_INIT_WITH_NOT_OWNED_KEY(int32,         int32)
D_UNORDERED_MAP_INIT_WITH_NOT_OWNED_KEY(int64,         int64)
D_UNORDERED_MAP_INIT_WITH_NOT_OWNED_KEY(u8,            u8)
D_UNORDERED_MAP_INIT_WITH_NOT_OWNED_KEY(u16,           u16)
D_UNORDERED_MAP_INIT_WITH_NOT_OWNED_KEY(u32,           u32)
D_UNORDERED_MAP_INIT_WITH_NOT_OWNED_KEY(u64,           u64)
D_UNORDERED_MAP_INIT_WITH_NOT_OWNED_KEY(usize,         usize)
D_UNORDERED_MAP_INIT_WITH_NOT_OWNED_KEY(bool,          bool)
D_UNORDERED_MAP_INIT_WITH_NOT_OWNED_KEY(char,          char)
D_UNORDERED_MAP_INIT_WITH_NOT_OWNED_KEY(str,           char *)
D_UNORDERED_MAP_INIT_WITH_NOT_OWNED_KEY(d_dyn_string,  DDynString *)
D_UNORDERED_MAP_INIT_WITH_NOT_OWNED_KEY(d_string_view, DStringView)

/* Pre-instantiated owned constructors */
D_UNORDERED_MAP_INIT_WITH_OWNED_KEY(str,          char *,       _free_str)
D_UNORDERED_MAP_INIT_WITH_OWNED_KEY(d_dyn_string, DDynString *, (FnPtrFreeElem)d_dyn_string_destroy)

/* -----------------------------------------------------------------------
 * Operations
 * -------------------------------------------------------------------- */

/**
 * @brief Inserts or updates the entry for @p key with a copy of @p value.
 *
 * If @p key is already present the old key and value destructors are called
 * (if configured) and then both the key and value slots are overwritten with
 * the new copies.
 *
 * @param map   Map to insert into. Must not be NULL.
 * @param key   Pointer to `key_size` bytes identifying the entry. Must not be NULL.
 * @param value Pointer to `value_size` bytes to store. Must not be NULL.
 * @return ::D_OK, ::D_ERR_INVALID_ARG if any argument is NULL,
 *         ::D_ERR_ALLOC on allocation failure (e.g. during rehash).
 *
 * @code{.c}
 *   int32 k = 1; int v = 100;
 *   d_unordered_map_insert(&map, &k, &v);
 * @endcode
 */
DResult d_unordered_map_insert(DUnorderedMap *map, void *key, void *value);

/**
 * @brief Returns a pointer to the value stored for @p key, or NULL if not found.
 *
 * @warning The returned pointer refers to internal map storage and is
 *          **invalidated** by any subsequent insert that triggers a rehash.
 *          Copy the value out if you need it to survive mutations.
 *
 * @param map The map to look up. Must not be NULL.
 * @param key Pointer to the key to search for. Must not be NULL.
 * @return Pointer to the stored value, or NULL if the key is absent or
 *         either argument is NULL.
 *
 * @code{.c}
 *   int32 k = 1;
 *   int *v = d_unordered_map_get(&map, &k);
 *   if (v) printf("value: %d\n", *v);
 * @endcode
 */
void *d_unordered_map_get(const DUnorderedMap *map, void *key);

/**
 * @brief Removes the entry for @p key and copies the stored key and value
 *        to the caller's buffers **without** calling any destructor.
 *
 * Use this when you want to take ownership of the stored data.
 *
 * @param map        Map to remove from. Must not be NULL.
 * @param     key        Pointer to the key to look up. Must not be NULL.
 * @param    slot_key   Buffer that receives the stored key bytes.
 *                           Must not be NULL; must be at least @c key_size bytes.
 * @param    slot_value Buffer that receives the stored value bytes.
 *                           Must not be NULL; must be at least @c value_size bytes.
 * @return ::D_OK, ::D_ERR_INVALID_ARG if any argument is NULL,
 *         ::D_ERR_NOT_EXIST if the key is not in the map.
 *
 * @code{.c}
 *   int32 k = 1, out_k = 0; int out_v = 0;
 *   d_unordered_map_remove(&map, &k, &out_k, &out_v);
 *   // out_k == 1, out_v == the stored value, no destructor called
 * @endcode
 */
DResult d_unordered_map_remove(DUnorderedMap *map, void *key, void *slot_key, void *slot_value);

/**
 * @brief Removes the entry for @p key and calls both destructors (if configured).
 *
 * Use this when the map should free the resources owned by the entry.
 *
 * @param map The map to delete from. Must not be NULL.
 * @param     key Pointer to the key to remove. Must not be NULL.
 * @return ::D_OK, ::D_ERR_INVALID_ARG if either argument is NULL,
 *         ::D_ERR_NOT_EXIST if the key is not in the map.
 *
 * @code{.c}
 *   int32 k = 1;
 *   d_unordered_map_delete(&map, &k); // destructors called
 * @endcode
 */
DResult d_unordered_map_delete(DUnorderedMap *map, void *key);

/**
 * @brief Calls destructors for all remaining entries, frees the table,
 *        and zeroes the struct.
 *
 * Safe to call on a NULL pointer (no-op). After this call @p map must not
 * be used without re-initialisation.
 *
 * @param map Map to destroy. May be NULL.
 */
void d_unordered_map_destroy(DUnorderedMap *map);

/**
 * @brief Writes the current number of key-value pairs into @p size.
 *
 * @param  d_unordered_map Map to query. Must not be NULL.
 * @param size            Receives the entry count. Must not be NULL.
 * @return ::D_OK, ::D_ERR_INVALID_ARG if either argument is NULL.
 */
DResult d_unordered_map_get_size(const DUnorderedMap *d_unordered_map, usize *size);

/**
 * @brief Writes the current table capacity into @p capacity.
 *
 * @param  d_unordered_map Map to query. Must not be NULL.
 * @param capacity        Receives the capacity. Must not be NULL.
 * @return ::D_OK, ::D_ERR_INVALID_ARG if either argument is NULL.
 */
DResult d_unordered_map_get_capacity(const DUnorderedMap *d_unordered_map, usize *capacity);

/** @} */ /* end of d_unordered_map group */

#endif
